/*
 * blue - object composition environment for csound
 * Copyright (c) 2000-2007 Steven Yi (stevenyi@gmail.com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by  the Free Software Foundation; either version 2 of the License or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation Inc., 59 Temple Place - Suite 330,
 * Boston, MA  02111-1307 USA
 */
package blue.ui.core.mixer;

import blue.mixer.*;
import java.awt.BorderLayout;

import javax.swing.event.DocumentEvent;

import blue.WindowSettingManager;
import blue.WindowSettingsSavable;
import blue.event.SimpleDocumentListener;
import blue.utility.GUI;
import electric.xml.Element;
import java.awt.Frame;

public class EffectEditorDialog extends javax.swing.JDialog implements
        WindowSettingsSavable {
    private Effect effect = null;

    EffectEditor effectEditor = new EffectEditor();

    /** Creates new form EffectEditorDialog2 */
    public EffectEditorDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        centerPanel.add(effectEditor, BorderLayout.CENTER);

        nameText.getDocument().addDocumentListener(
                new SimpleDocumentListener() {

                    public void documentChanged(DocumentEvent e) {
                        if (effect != null) {
                            effect.setName(nameText.getText());
                        }
                    }

                });

        GUI.centerOnScreen(this);

        WindowSettingManager.getInstance().registerWindow("EffectEditorDialog",
                this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        centerPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setTitle("Edit Effect");
        jLabel1.setText("Name:");

        nameText.setText("jTextField1");

        centerPanel.setLayout(new java.awt.BorderLayout());

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(jLabel1)
                        .addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED).add(
                                nameText,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                425, Short.MAX_VALUE).addContainerGap()).add(
                org.jdesktop.layout.GroupLayout.TRAILING,
                layout.createSequentialGroup().addContainerGap(418,
                        Short.MAX_VALUE).add(closeButton).addContainerGap())
                .add(centerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        499, Short.MAX_VALUE));
        layout
                .setVerticalGroup(layout
                        .createParallelGroup(
                                org.jdesktop.layout.GroupLayout.LEADING)
                        .add(
                                layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.BASELINE)
                                                        .add(jLabel1)
                                                        .add(
                                                                nameText,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(
                                                centerPanel,
                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                247, Short.MAX_VALUE)
                                        .addPreferredGap(
                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(closeButton).addContainerGap()));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_closeButtonActionPerformed
        hide();
    }// GEN-LAST:event_closeButtonActionPerformed

    public void setEffect(Effect effect) {
        this.effect = effect;

        this.nameText.setText(this.effect.getName());
        effectEditor.setEffect(this.effect);
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EffectEditorDialog(null, true).setVisible(true);
            }
        });
    }

    public void loadWindowSettings(Element settings) {
        WindowSettingManager.setBasicSettings(settings, this);
    }

    public Element saveWindowSettings() {
        return WindowSettingManager.getBasicSettings(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;

    private javax.swing.JButton closeButton;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables

}
