/*
 * SendEditPanel.java
 *
 * Created on February 19, 2007, 7:03 PM
 */

package blue.ui.core.mixer;

import blue.mixer.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.MessageFormat;
import java.util.Locale;

import javax.swing.ComboBoxModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * 
 * @author steven
 */
public class SendEditPanel extends javax.swing.JPanel implements
        PropertyChangeListener {

    private static MessageFormat format = new MessageFormat("{0,number,#.##}",
            Locale.ENGLISH);

    Send send = null;

    boolean updating = false;

    /** Creates new form SendEditPanel */
    public SendEditPanel() {
        initComponents();

        amountSlider.setMinimum(0);
        amountSlider.setMaximum(100);

        amountSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                float val = amountSlider.getValue() / 100.0f;
                valueLabel.setText(format
                        .format(new Object[] { new Float(val) }));
                if (send != null && !updating) {
                    send.setLevel(val);
                }
            }
        });

        channelComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (send != null) {
                    send.setSendChannel((String) channelComboBox
                            .getSelectedItem());
                }
            }
        });

    }

    public void addNotify() {
        super.addNotify();
        if (this.send != null) {
            this.send.addPropertyChangeListener(this);
        }
    }

    public void removeNotify() {
        super.removeNotify();

        if (this.send != null) {
            this.send.removePropertyChangeListener(this);
        }
    }

    public void setSend(Send send) {
        if (this.send != null) {
            this.send.removePropertyChangeListener(this);
        }

        this.send = null;
        updating = true;

        amountSlider.setValue((int) (send.getLevel() * 100));
        channelComboBox.setSelectedItem(send.getSendChannel());

        this.send = send;
        updating = false;

        this.send.addPropertyChangeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        channelComboBox = new javax.swing.JComboBox();
        amountSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        jLabel1.setText("Send Channel");

        jLabel2.setText("Amount");

        channelComboBox.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("0.0");

        jLabel4.setText("1.0");

        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueLabel.setText("Value");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
                this);
        this.setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(
                                org.jdesktop.layout.GroupLayout.LEADING)
                        .add(
                                layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(jLabel1).add(
                                                                jLabel2))
                                        .addPreferredGap(
                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(
                                                                layout
                                                                        .createSequentialGroup()
                                                                        .add(
                                                                                jLabel3)
                                                                        .addPreferredGap(
                                                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(
                                                                                valueLabel,
                                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                229,
                                                                                Short.MAX_VALUE)
                                                                        .addPreferredGap(
                                                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                                                        .add(
                                                                                jLabel4))
                                                        .add(channelComboBox,
                                                                0, 279,
                                                                Short.MAX_VALUE)
                                                        .add(
                                                                amountSlider,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                279,
                                                                Short.MAX_VALUE))
                                        .addContainerGap()));
        layout
                .setVerticalGroup(layout
                        .createParallelGroup(
                                org.jdesktop.layout.GroupLayout.LEADING)
                        .add(
                                layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.BASELINE)
                                                        .add(jLabel1)
                                                        .add(
                                                                channelComboBox,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(jLabel2)
                                                        .add(
                                                                amountSlider,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(
                                                layout
                                                        .createParallelGroup(
                                                                org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(
                                                                layout
                                                                        .createParallelGroup(
                                                                                org.jdesktop.layout.GroupLayout.BASELINE)
                                                                        .add(
                                                                                jLabel3)
                                                                        .add(
                                                                                valueLabel))
                                                        .add(jLabel4))
                                        .addContainerGap(
                                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    void setComboBoxModel(ComboBoxModel comboBoxModel) {
        channelComboBox.setModel(comboBoxModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider amountSlider;

    private javax.swing.JComboBox channelComboBox;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel valueLabel;

    // End of variables declaration//GEN-END:variables

    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("level")) {
            updating = true;

            amountSlider.setValue((int) (send.getLevel() * 100));

            updating = false;
        }
    }

}
