/*
 * SendEditPanel.java
 *
 * Created on February 19, 2007, 7:03 PM
 */

package blue.ui.core.mixer;

import blue.mixer.*;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.MessageFormat;
import java.util.Locale;
import javax.swing.ComboBoxModel;
import javax.swing.event.ChangeEvent;

/**
 * 
 * @author steven
 */
public class SendEditPanel extends javax.swing.JPanel implements
        PropertyChangeListener {

    private static MessageFormat format = new MessageFormat("{0,number,#.##}",
            Locale.ENGLISH);

    Send send = null;

    boolean updating = false;

    /** Creates new form SendEditPanel */
    public SendEditPanel() {
        initComponents();

        amountSlider.setMinimum(0);
        amountSlider.setMaximum(100);

        amountSlider.addChangeListener((ChangeEvent e) -> {
            float val = amountSlider.getValue() / 100.0f;
            valueLabel.setText(format
                    .format(new Object[] { new Float(val) }));
            if (send != null && !updating) {
                send.setLevel(val);
            }
        });

        channelComboBox.addActionListener((ActionEvent e) -> {
            if (send != null) {
                send.setSendChannel((String) channelComboBox
                        .getSelectedItem());
            }
        });

    }

    @Override
    public void addNotify() {
        super.addNotify();
        if (this.send != null) {
            this.send.addPropertyChangeListener(this);
        }
    }

    @Override
    public void removeNotify() {
        super.removeNotify();

        if (this.send != null) {
            this.send.removePropertyChangeListener(this);
        }
    }

    public void setSend(Send send) {
        if (this.send != null) {
            this.send.removePropertyChangeListener(this);
        }

        this.send = null;
        updating = true;

        amountSlider.setValue((int) (send.getLevel() * 100));
        channelComboBox.setSelectedItem(send.getSendChannel());

        this.send = send;
        updating = false;

        this.send.addPropertyChangeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        channelComboBox = new javax.swing.JComboBox();
        amountSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        jLabel1.setText("Send Channel");

        jLabel2.setText("Amount");

        channelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("0.0");

        jLabel4.setText("1.0");

        valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueLabel.setText("Value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(channelComboBox, 0, 285, Short.MAX_VALUE)
                    .addComponent(amountSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(channelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(amountSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(valueLabel))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void setComboBoxModel(ComboBoxModel comboBoxModel) {
        channelComboBox.setModel(comboBoxModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider amountSlider;
    private javax.swing.JComboBox channelComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals("level")) {
            updating = true;

            amountSlider.setValue((int) (send.getLevel() * 100));

            updating = false;
        }
    }

}
