import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const execFileAsync = promisify(execFile);
const distBinaryPath = path.resolve(
  fileURLToPath(new URL('../dist/blue-cli.cjs', import.meta.url)),
);

describe('blue-cli binary smoke test', () => {
  it('compiles a minimal project through the built binary', async () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'blue-cli-smoke-'));
    const projectPath = path.join(tempDir, 'project.blue');
    const outputPath = path.join(tempDir, 'project.csd');
    fs.writeFileSync(
      projectPath,
      '<blueData version="5.0.0"><projectProperties/></blueData>',
      'utf8',
    );

    await execFileAsync('node', [distBinaryPath, 'compile', '-p', projectPath, '-o', outputPath]);

    const output = fs.readFileSync(outputPath, 'utf8');

    expect(output).toContain('<CsoundSynthesizer>');
    expect(output).toContain('Generated by blue 2.10.1');
  });
});
