packages:
  - packages/*
  - native/*

allowBuilds:
  '@electron/rebuild': true
  electron: true
  electron-winstaller: true
  esbuild: true
  zeromq: true

packageExtensions:
  vite-plugin-electron@0.29.1:
    peerDependencies:
      vite: ^7.3.2
