packages:
  - packages/*
  - native/*

onlyBuiltDependencies:
  - '@electron/rebuild'
  - electron
  - electron-winstaller
  - esbuild
  - zeromq

confirmModulesPurge: false

packageExtensions:
  vite-plugin-electron@0.29.1:
    peerDependencies:
      vite: ^7.3.2
