/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package blue.ui.core.tables;

import blue.Tables;
import blue.projects.BlueProject;
import blue.projects.BlueProjectManager;
import blue.ui.nbutilities.MimeTypeEditorComponent;
import blue.ui.utilities.SimpleDocumentListener;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.Serializable;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.undo.UndoManager;
import org.openide.awt.UndoRedo;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class TablesTopComponent extends TopComponent {

    private static TablesTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    
    private MimeTypeEditorComponent tablesText = new MimeTypeEditorComponent("text/x-csound-sco");

    private static final String PREFERRED_ID = "TablesTopComponent";

    private Tables tables = null;
    
    UndoManager undo = new UndoRedo.Manager();

    private TablesTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TablesTopComponent.class, "CTL_TablesTopComponent"));
        setToolTipText(NbBundle.getMessage(TablesTopComponent.class, "HINT_TablesTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));

        BlueProjectManager.getInstance().addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (BlueProjectManager.CURRENT_PROJECT.equals(evt.getPropertyName())) {
                    tables = null;
                    reinitialize();
                }
            }
        });

        reinitialize();

        tablesText.getDocument().addDocumentListener(new SimpleDocumentListener() {

            @Override
            public void documentChanged(DocumentEvent e) {
                if (tables != null) {
                    tables.setTables(tablesText.getText());
                }
            }
        });
        
        tablesText.setUndoManager(undo);
        tablesText.getDocument().addUndoableEditListener(undo);
        this.add(tablesText,BorderLayout.CENTER);
    }

     private void reinitialize() {
        BlueProject project = BlueProjectManager.getInstance().getCurrentProject();
        if (project == null) {
            tablesText.setText("");
            tablesText.getJEditorPane().setEditable(false);
        } else {
            Tables localTables = project.getData().getTableSet();
            tablesText.setText(localTables.getTables());
            tablesText.getJEditorPane().setEditable(true);
            tables = localTables;
        }
        undo.discardAllEdits();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized TablesTopComponent getDefault() {
        if (instance == null) {
            instance = new TablesTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the TablesTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized TablesTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(TablesTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof TablesTopComponent) {
            return (TablesTopComponent) win;
        }
        Logger.getLogger(TablesTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return TablesTopComponent.getDefault();
        }
    }
}
