/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blue.orchestra.editor.blueSynthBuilder.swing;

import blue.orchestra.blueSynthBuilder.GridSettings;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author stevenyi
 */
public class GridSettingsEditPanel extends javax.swing.JPanel {

    GridSettings gridSettings = null;

    /**
     * Creates new form GridSettingsEditPanel
     */
    public GridSettingsEditPanel() {
        initComponents();

        widthSpinner.addChangeListener(ce -> {
            if (gridSettings != null) {
                var number = (Number) widthSpinner.getValue();
                gridSettings.setWidth(number.intValue());
            }
        });
        heightSpinner.addChangeListener(ce -> {
            if (gridSettings != null) {
                var number = (Number) heightSpinner.getValue();
                gridSettings.setHeight(number.intValue());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        heightSpinner = new javax.swing.JSpinner();
        snapEnabledBox = new javax.swing.JCheckBox();
        gridStyleComboBox = new javax.swing.JComboBox<>();
        widthSpinner = new javax.swing.JSpinner();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GridSettingsEditPanel.class, "GridSettingsEditPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(GridSettingsEditPanel.class, "GridSettingsEditPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(GridSettingsEditPanel.class, "GridSettingsEditPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(GridSettingsEditPanel.class, "GridSettingsEditPanel.jLabel4.text")); // NOI18N

        heightSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        org.openide.awt.Mnemonics.setLocalizedText(snapEnabledBox, org.openide.util.NbBundle.getMessage(GridSettingsEditPanel.class, "GridSettingsEditPanel.snapEnabledBox.text")); // NOI18N
        snapEnabledBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapEnabledBoxActionPerformed(evt);
            }
        });

        gridStyleComboBox.setModel(new DefaultComboBoxModel(GridSettings.GridStyle.values()));
        gridStyleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridStyleComboBoxActionPerformed(evt);
            }
        });

        widthSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gridStyleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(snapEnabledBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(heightSpinner))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gridStyleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(snapEnabledBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(widthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gridStyleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridStyleComboBoxActionPerformed
        if(gridSettings != null) {
            gridSettings.setGridStyle((GridSettings.GridStyle) gridStyleComboBox.getSelectedItem());
        }
    }//GEN-LAST:event_gridStyleComboBoxActionPerformed

    private void snapEnabledBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapEnabledBoxActionPerformed
        if(gridSettings != null) {
            gridSettings.setSnapEnabled(snapEnabledBox.isSelected());
        }
    }//GEN-LAST:event_snapEnabledBoxActionPerformed

    public void editGridSettings(GridSettings gridSettings) {
        this.gridSettings = null;
        
        heightSpinner.setValue(gridSettings.getHeight());
        widthSpinner.setValue(gridSettings.getWidth());
        gridStyleComboBox.setSelectedItem(gridSettings.getGridStyle());
        snapEnabledBox.setSelected(gridSettings.isSnapEnabled());
        
        this.gridSettings = gridSettings;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<GridSettings.GridStyle> gridStyleComboBox;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox snapEnabledBox;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables
}
