/*
 * blue - object composition environment for csound Copyright (c) 2000-2009
 * Steven Yi (stevenyi@gmail.com)
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License or (at your option) any
 * later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.LIB. If not, write to the Free
 * Software Foundation Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307
 * USA
 */
package blue.settings;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

final class TextColorsPanel extends javax.swing.JPanel {

    private final TextColorsOptionsPanelController controller;

    private boolean loading = false;

    TextColorsPanel(TextColorsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();

        PropertyChangeListener pcl = new PropertyChangeListener() {

            public void propertyChange(PropertyChangeEvent evt) {
                if ("colorSelectionValue".equals(evt.getPropertyName())) {
                    if (!loading) {
                        TextColorsPanel.this.controller.changed();
                    }
                }
            }
        };

        textNormal.addPropertyChangeListener(pcl);
        textComment.addPropertyChangeListener(pcl);
        textKeyword.addPropertyChangeListener(pcl);
        textQuote.addPropertyChangeListener(pcl);
        textVariable.addPropertyChangeListener(pcl);
        textBackground.addPropertyChangeListener(pcl);
        textPfield.addPropertyChangeListener(pcl);
		fontSizeSpinner.addChangeListener(new ChangeListener() {

			public void stateChanged(ChangeEvent ce) {
				if (!loading) {
					TextColorsPanel.this.controller.changed();
				}
			}
		});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resetColorsButton = new javax.swing.JButton();
        useBlueDefaultsButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textComment = new blue.settings.ColorSelectionPanel();
        textNormal = new blue.settings.ColorSelectionPanel();
        textKeyword = new blue.settings.ColorSelectionPanel();
        textQuote = new blue.settings.ColorSelectionPanel();
        textVariable = new blue.settings.ColorSelectionPanel();
        textBackground = new blue.settings.ColorSelectionPanel();
        textPfield = new blue.settings.ColorSelectionPanel();
        jLabel7 = new javax.swing.JLabel();
        fontSizeSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(resetColorsButton, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.resetColorsButton.text")); // NOI18N
        resetColorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetColorsButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(useBlueDefaultsButton, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.useBlueDefaultsButton.text")); // NOI18N
        useBlueDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useBlueDefaultsButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout textCommentLayout = new javax.swing.GroupLayout(textComment);
        textComment.setLayout(textCommentLayout);
        textCommentLayout.setHorizontalGroup(
            textCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textCommentLayout.setVerticalGroup(
            textCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout textNormalLayout = new javax.swing.GroupLayout(textNormal);
        textNormal.setLayout(textNormalLayout);
        textNormalLayout.setHorizontalGroup(
            textNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textNormalLayout.setVerticalGroup(
            textNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout textKeywordLayout = new javax.swing.GroupLayout(textKeyword);
        textKeyword.setLayout(textKeywordLayout);
        textKeywordLayout.setHorizontalGroup(
            textKeywordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textKeywordLayout.setVerticalGroup(
            textKeywordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout textQuoteLayout = new javax.swing.GroupLayout(textQuote);
        textQuote.setLayout(textQuoteLayout);
        textQuoteLayout.setHorizontalGroup(
            textQuoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textQuoteLayout.setVerticalGroup(
            textQuoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout textVariableLayout = new javax.swing.GroupLayout(textVariable);
        textVariable.setLayout(textVariableLayout);
        textVariableLayout.setHorizontalGroup(
            textVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textVariableLayout.setVerticalGroup(
            textVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout textBackgroundLayout = new javax.swing.GroupLayout(textBackground);
        textBackground.setLayout(textBackgroundLayout);
        textBackgroundLayout.setHorizontalGroup(
            textBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textBackgroundLayout.setVerticalGroup(
            textBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout textPfieldLayout = new javax.swing.GroupLayout(textPfield);
        textPfield.setLayout(textPfieldLayout);
        textPfieldLayout.setHorizontalGroup(
            textPfieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );
        textPfieldLayout.setVerticalGroup(
            textPfieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel7.text")); // NOI18N

        fontSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(12, 8, 32, 1));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(TextColorsPanel.class, "TextColorsPanel.jLabel8.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetColorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addComponent(useBlueDefaultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textComment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textVariable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textQuote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textPfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textKeyword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textNormal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fontSizeSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                                .addContainerGap())))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(textKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textPfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textQuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fontSizeSpinner))
                .addGap(12, 12, 12)
                .addComponent(resetColorsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useBlueDefaultsButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetColorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetColorsButtonActionPerformed
        resetColors();
    }//GEN-LAST:event_resetColorsButtonActionPerformed

    private void useBlueDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useBlueDefaultsButtonActionPerformed
        defaultColors();
    }//GEN-LAST:event_useBlueDefaultsButtonActionPerformed

    protected void defaultColors() {
        textNormal.setColor(Color.WHITE);
        textComment.setColor(Color.GRAY);
        textKeyword.setColor(Color.ORANGE);
        textQuote.setColor(Color.PINK);
        textVariable.setColor(Color.PINK);
        textBackground.setColor(Color.BLACK);
        textPfield.setColor(Color.WHITE);
		fontSizeSpinner.setValue(12);
    }

    protected void resetColors() {
        load();
    }

    void load() {
        loading = true;

        TextColorsSettings settings = TextColorsSettings.getInstance();

        textNormal.setColor(settings.blueSyntaxNormal);
        textComment.setColor(settings.blueSyntaxComment);
        textKeyword.setColor(settings.blueSyntaxKeyword);
        textQuote.setColor(settings.blueSyntaxQuote);
        textVariable.setColor(settings.blueSyntaxVariable);
        textBackground.setColor(settings.blueSyntaxBackground);
        textPfield.setColor(settings.blueSyntaxPfield);
		fontSizeSpinner.setValue(settings.blueSyntaxFontSize);

        loading = false;
    }

    void store() {

        TextColorsSettings settings = TextColorsSettings.getInstance();

        settings.blueSyntaxNormal = textNormal.getColor();
        settings.blueSyntaxComment = textComment.getColor();
        settings.blueSyntaxKeyword = textKeyword.getColor();
        settings.blueSyntaxQuote = textQuote.getColor();
        settings.blueSyntaxVariable = textVariable.getColor();
        settings.blueSyntaxBackground = textBackground.getColor();
        settings.blueSyntaxPfield = textPfield.getColor();
		settings.blueSyntaxFontSize = ((Integer)fontSizeSpinner.getValue()).intValue();

        settings.save();
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner fontSizeSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton resetColorsButton;
    private blue.settings.ColorSelectionPanel textBackground;
    private blue.settings.ColorSelectionPanel textComment;
    private blue.settings.ColorSelectionPanel textKeyword;
    private blue.settings.ColorSelectionPanel textNormal;
    private blue.settings.ColorSelectionPanel textPfield;
    private blue.settings.ColorSelectionPanel textQuote;
    private blue.settings.ColorSelectionPanel textVariable;
    private javax.swing.JButton useBlueDefaultsButton;
    // End of variables declaration//GEN-END:variables
}
