/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectInformationPanel.java
 *
 * Created on Feb 8, 2009, 8:37:17 PM
 */
package blue.ui.core.project;

import blue.ProjectProperties;
import blue.event.SimpleDocumentListener;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author steven
 */
public class ProjectInformationPanel extends javax.swing.JPanel {

    private ProjectProperties projectProperties = null;

    /** Creates new form ProjectInformationPanel */
    public ProjectInformationPanel() {
        initComponents();

        titleText.getDocument().addDocumentListener(
                new SimpleDocumentListener() {

                    public void documentChanged(DocumentEvent e) {
                        if (projectProperties != null) {
                            projectProperties.title = titleText.getText();
                        }
                    }
                });

        authorText.getDocument().addDocumentListener(
                new SimpleDocumentListener() {

                    public void documentChanged(DocumentEvent e) {
                        if (projectProperties != null) {
                            projectProperties.author = authorText.getText();
                        }
                    }
                });

        notesText.getDocument().addDocumentListener(
                new SimpleDocumentListener() {

                    public void documentChanged(DocumentEvent e) {
                        if (projectProperties != null) {
                            projectProperties.notes = notesText.getText();
                        }
                    }
                });
    }

    public void setProjectProperties(ProjectProperties projectProperties) {
        this.projectProperties = null;

        if (projectProperties != null) {
            titleText.setText(projectProperties.title);
            authorText.setText(projectProperties.author);
            notesText.setText(projectProperties.notes);

            this.projectProperties = projectProperties;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesText = new javax.swing.JTextArea();
        authorText = new javax.swing.JTextField();
        titleText = new javax.swing.JTextField();

        jLabel12.setText(org.openide.util.NbBundle.getMessage(ProjectInformationPanel.class, "ProjectInformationPanel.jLabel12.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(ProjectInformationPanel.class, "ProjectInformationPanel.jLabel13.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(ProjectInformationPanel.class, "ProjectInformationPanel.jLabel10.text")); // NOI18N

        notesText.setColumns(20);
        notesText.setLineWrap(true);
        notesText.setRows(5);
        notesText.setTabSize(4);
        jScrollPane1.setViewportView(notesText);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel12)
                    .add(jLabel13)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .add(authorText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .add(titleText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(titleText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(authorText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel13)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea notesText;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables

}
