/*
 * CauchyEditor.java
 *
 * Created on April 22, 2008, 9:35 PM
 */
package blue.soundObject.editor.jmask.probability;

import blue.soundObject.editor.jmask.DurationSettable;
import blue.soundObject.jmask.probability.Cauchy;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  syi
 */
public class CauchyEditor extends javax.swing.JPanel implements DurationSettable {

    private Cauchy cauchy = null;

    public CauchyEditor(Cauchy cauchy) {
        initComponents();

        alphaTableEditor.setMinMaxEnabled(false);
        muTableEditor.setMinMaxEnabled(false);

        alphaTableEditor.setTable(cauchy.getAlphaTable());
        muTableEditor.setTable(cauchy.getMuTable());

        alphaSpinner.setModel(
                new SpinnerNumberModel(cauchy.getAlpha(), 0.0, 1.0, 0.1));

        muSpinner.setModel(
                new SpinnerNumberModel(cauchy.getMu(), 0.0, 1.0, 0.1));

        spreadTypeComboBox.setSelectedIndex(cauchy.isAlphaTableEnabled() ? 1 : 0);
        meanTypeComboBox.setSelectedIndex(cauchy.isMuTableEnabled() ? 1 : 0);
        
        this.cauchy = cauchy;
        
        updateDisplay();
    }
    
    private void updateDisplay() {
        alphaSpinner.setVisible(!this.cauchy.isAlphaTableEnabled());
        alphaTableEditor.setVisible(this.cauchy.isAlphaTableEnabled());
        muSpinner.setVisible(!this.cauchy.isMuTableEnabled());
        muTableEditor.setVisible(this.cauchy.isMuTableEnabled());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aButtonGroup = new javax.swing.ButtonGroup();
        bButtonGroup = new javax.swing.ButtonGroup();
        alphaSpinner = new javax.swing.JSpinner();
        alphaTableEditor = new blue.soundObject.editor.jmask.TableEditor();
        muSpinner = new javax.swing.JSpinner();
        muTableEditor = new blue.soundObject.editor.jmask.TableEditor();
        spreadTypeComboBox = new javax.swing.JComboBox();
        meanTypeComboBox = new javax.swing.JComboBox();

        alphaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaSpinnerStateChanged(evt);
            }
        });

        muSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                muSpinnerStateChanged(evt);
            }
        });

        spreadTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spread/alpha (Constant)", "Spread/alpha (Table)" }));
        spreadTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spreadTypeComboBoxActionPerformed(evt);
            }
        });

        meanTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mean/mu (Constant)", "Mean/mu (Table)" }));
        meanTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meanTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spreadTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alphaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alphaTableEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(muTableEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, meanTypeComboBox, spreadTypeComboBox);

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spreadTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alphaTableEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muTableEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void alphaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSpinnerStateChanged
        if (this.cauchy != null) {
            this.cauchy.setAlpha(((Double) alphaSpinner.getValue()).doubleValue());
        }
}//GEN-LAST:event_alphaSpinnerStateChanged

    private void muSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_muSpinnerStateChanged
        if (this.cauchy != null) {
            this.cauchy.setMu(((Double) muSpinner.getValue()).doubleValue());
        }
}//GEN-LAST:event_muSpinnerStateChanged

private void spreadTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spreadTypeComboBoxActionPerformed
    if(this.cauchy != null) {
        this.cauchy.setAlphaTableEnabled(spreadTypeComboBox.getSelectedIndex() == 1);
        updateDisplay();
    }
}//GEN-LAST:event_spreadTypeComboBoxActionPerformed

private void meanTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meanTypeComboBoxActionPerformed
    if(this.cauchy != null) {
        this.cauchy.setMuTableEnabled(meanTypeComboBox.getSelectedIndex() == 1);
        updateDisplay();
    }
}//GEN-LAST:event_meanTypeComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aButtonGroup;
    private javax.swing.JSpinner alphaSpinner;
    private blue.soundObject.editor.jmask.TableEditor alphaTableEditor;
    private javax.swing.ButtonGroup bButtonGroup;
    private javax.swing.JComboBox meanTypeComboBox;
    private javax.swing.JSpinner muSpinner;
    private blue.soundObject.editor.jmask.TableEditor muTableEditor;
    private javax.swing.JComboBox spreadTypeComboBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setDuration(double duration) {
        alphaTableEditor.setDuration(duration);
        muTableEditor.setDuration(duration);
    }
}
