#!/usr/bin/env node
/**
 * Remove all generated build artifacts so the next `pnpm app:build` or
 * `pnpm app:package` starts from a clean state.
 *
 * Removed:
 *   - packages/.../dist               TypeScript / Vite build output
 *   - packages/blue-app/release       electron-builder output (DMG, NSIS, AppImage, .app bundles)
 *   - packages/blue-java/target       Maven build output
 *   - packages/blue-app/assets/java/blue-java.jar
 *                                       Maven-generated helper JAR (gitignored)
 *   - packages/blue-app/.engine-stage Electron native-sidecar staging
 *   - native/blue-engine/build-*      CMake build trees
 *   - native/blue-engine/dist         verified native artifact output
 *   - native/blue-engine/vcpkg_installed
 *                                       package-local vcpkg installation
 *
 * Not touched:
 *   - packages/blue-app/assets/java/pythonLib
 *       These Python files are TRACKED in git (committed during SPEC 050)
 *       even though Maven also copies them from
 *       packages/blue-java/src/main/resources/jython/pythonLib.
 *       Removing them would show up as deletions in `git status`.
 *   - node_modules (use `pnpm install --force` to rebuild native addons)
 *   - source files, git history, user settings, program-settings.json
 *
 * Usage: node scripts/clean.mjs [--verbose]
 */

import { rmSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const verbose = process.argv.includes('--verbose');

/** @param {string} relPath */
function remove(relPath) {
  const abs = join(repoRoot, relPath);
  if (!existsSync(abs)) {
    if (verbose) process.stderr.write(`[skip] (missing) ${relPath}\n`);
    return;
  }
  try {
    rmSync(abs, { recursive: true, force: true });
    process.stderr.write(`[ok] removed ${relPath}\n`);
  } catch (error) {
    process.stderr.write(
      `[FAIL] could not remove ${relPath}: ${error instanceof Error ? error.message : String(error)}\n`,
    );
  }
}

// 1. Per-package TypeScript/Vite build output.
const packagesDir = join(repoRoot, 'packages');
for (const entry of readdirSync(packagesDir)) {
  const pkgPath = join(packagesDir, entry);
  if (!statSync(pkgPath).isDirectory()) continue;
  remove(`packages/${entry}/dist`);
}

// 2. electron-builder output (unpacked apps, installers, manifests).
remove('packages/blue-app/release');
remove('packages/blue-app/.engine-stage');
remove('packages/blue-app/release-metadata.json');

// 3. Maven build output for the Java helper.
remove('packages/blue-java/target');

// 4. Maven-generated helper JAR (gitignored). Regenerated by
//    `pnpm --filter @blue/java-runtime build`.
//    NOTE: do NOT remove pythonLib/ - those files are tracked in git
//    (committed during SPEC 050 Jython support). Maven does copy them
//    from packages/blue-java/src/main/resources/jython/pythonLib, but
//    the working-tree copies must be preserved to avoid spurious
//    `git status` deletions.
remove('packages/blue-app/assets/java/blue-java.jar');

// 5. Native sidecar build and derived artifact output.
const nativeEngineDir = join(repoRoot, 'native/blue-engine');
if (existsSync(nativeEngineDir)) {
  for (const entry of readdirSync(nativeEngineDir)) {
    if (entry === 'build' || entry.startsWith('build-')) {
      remove(`native/blue-engine/${entry}`);
    }
  }
}
remove('native/blue-engine/dist');
remove('native/blue-engine/vcpkg_installed');

process.stderr.write('\nClean complete. Run `pnpm app:build` to rebuild.\n');
