/*
 * BetaEditor.java
 *
 * Created on April 22, 2008, 9:35 PM
 */
package blue.soundObject.editor.jmask.probability;

import blue.soundObject.editor.jmask.DurationSettable;
import blue.soundObject.jmask.probability.Beta;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  syi
 */
public class BetaEditor extends javax.swing.JPanel implements DurationSettable {

    private Beta beta = null;

    /** Creates new form BetaEditor */
    public BetaEditor(Beta beta) {
        initComponents();

        aTableEditor.setMinMaxEnabled(false);
        bTableEditor.setMinMaxEnabled(false);

        aTableEditor.setTable(beta.getATable());
        bTableEditor.setTable(beta.getBTable());

        aSpinner.setModel(
                new SpinnerNumberModel(beta.getA(), 0.0, 1.0, 0.1));

        bSpinner.setModel(
                new SpinnerNumberModel(beta.getB(), 0.0, 1.0, 0.1));

        aTypeComboBox.setSelectedIndex(beta.isATableEnabled() ? 1 : 0);
        bTypeComboBox.setSelectedIndex(beta.isBTableEnabled() ? 1 : 0);
                
        this.beta = beta;
        
        updateDisplay();
    }
    
    private void updateDisplay() {
        aSpinner.setVisible(!this.beta.isATableEnabled());
        aTableEditor.setVisible(this.beta.isATableEnabled());
        bSpinner.setVisible(!this.beta.isBTableEnabled());
        bTableEditor.setVisible(this.beta.isBTableEnabled());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aButtonGroup = new javax.swing.ButtonGroup();
        bButtonGroup = new javax.swing.ButtonGroup();
        aSpinner = new javax.swing.JSpinner();
        aTableEditor = new blue.soundObject.editor.jmask.TableEditor();
        bSpinner = new javax.swing.JSpinner();
        bTableEditor = new blue.soundObject.editor.jmask.TableEditor();
        aTypeComboBox = new javax.swing.JComboBox();
        bTypeComboBox = new javax.swing.JComboBox();

        aSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aSpinnerStateChanged(evt);
            }
        });

        bSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bSpinnerStateChanged(evt);
            }
        });

        aTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a (Constant)", "a (Table)" }));
        aTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTypeComboBoxActionPerformed(evt);
            }
        });

        bTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "b (Constant)", "b (Table)" }));
        bTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTypeComboBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(aTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(bTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(aTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(aSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, bTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {aTypeComboBox, bTypeComboBox}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(aTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(aSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(aTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void aSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aSpinnerStateChanged
        if (this.beta != null) {
            this.beta.setA(((Double) aSpinner.getValue()).doubleValue());
        }
}//GEN-LAST:event_aSpinnerStateChanged

    private void bSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bSpinnerStateChanged
        if (this.beta != null) {
            this.beta.setB(((Double) bSpinner.getValue()).doubleValue());
        }
}//GEN-LAST:event_bSpinnerStateChanged

private void aTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTypeComboBoxActionPerformed
    if(this.beta != null) {
        this.beta.setATableEnabled(aTypeComboBox.getSelectedIndex() == 1);
        updateDisplay();
    }
}//GEN-LAST:event_aTypeComboBoxActionPerformed

private void bTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTypeComboBoxActionPerformed
    if(this.beta != null) {
        this.beta.setBTableEnabled(bTypeComboBox.getSelectedIndex() == 1);
        updateDisplay();
    }
}//GEN-LAST:event_bTypeComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aButtonGroup;
    private javax.swing.JSpinner aSpinner;
    private blue.soundObject.editor.jmask.TableEditor aTableEditor;
    private javax.swing.JComboBox aTypeComboBox;
    private javax.swing.ButtonGroup bButtonGroup;
    private javax.swing.JSpinner bSpinner;
    private blue.soundObject.editor.jmask.TableEditor bTableEditor;
    private javax.swing.JComboBox bTypeComboBox;
    // End of variables declaration//GEN-END:variables

    public void setDuration(double duration) {
        aTableEditor.setDuration(duration);
        bTableEditor.setDuration(duration);
    }
}
