/*
 * WeibullEditor.java
 *
 * Created on April 22, 2008, 9:35 PM
 */
package blue.soundObject.editor.jmask.probability;

import blue.soundObject.editor.jmask.DurationSettable;
import blue.soundObject.jmask.probability.Weibull;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  syi
 */
public class WeibullEditor extends javax.swing.JPanel implements DurationSettable {

    private Weibull weibull = null;

    public WeibullEditor(Weibull weibull) {
        initComponents();

        sTableEditor.setMinMaxEnabled(false);
        tTableEditor.setPositiveValues();

        sTableEditor.setTable(weibull.getSTable());
        tTableEditor.setTable(weibull.getTTable());

        sSpinner.setModel(
                new SpinnerNumberModel(weibull.getS(), 0.0, 1.0, 0.1));

        tSpinner.setModel(
                new SpinnerNumberModel(
                    new Double(weibull.getT()), 
                    new Double(Double.MIN_VALUE),
                    null, new Double(0.1)));

        sTypeComboBox.setSelectedIndex(weibull.isSTableEnabled() ? 1 : 0);
        tTypeComboBox.setSelectedIndex(weibull.isTTableEnabled() ? 1 : 0);
        
        this.weibull = weibull;
        
        updateDisplay();
    }
    
    private void updateDisplay() {
        sSpinner.setVisible(!this.weibull.isSTableEnabled());
        sTableEditor.setVisible(this.weibull.isSTableEnabled());
        tSpinner.setVisible(!this.weibull.isTTableEnabled());
        tTableEditor.setVisible(this.weibull.isTTableEnabled());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aButtonGroup = new javax.swing.ButtonGroup();
        bButtonGroup = new javax.swing.ButtonGroup();
        sSpinner = new javax.swing.JSpinner();
        sTableEditor = new blue.soundObject.editor.jmask.TableEditor();
        tSpinner = new javax.swing.JSpinner();
        tTableEditor = new blue.soundObject.editor.jmask.TableEditor();
        sTypeComboBox = new javax.swing.JComboBox();
        tTypeComboBox = new javax.swing.JComboBox();

        sSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sSpinnerStateChanged(evt);
            }
        });

        tSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tSpinnerStateChanged(evt);
            }
        });

        sTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "s (Constant)", "s (Table)" }));
        sTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTypeComboBoxActionPerformed(evt);
            }
        });

        tTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "t (Constant)", "t (Table)" }));
        tTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTypeComboBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(sTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(tTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(tSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(sTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
                    .add(tTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {sTypeComboBox, tTypeComboBox}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tTypeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tTableEditor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void sSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sSpinnerStateChanged
        if (this.weibull != null) {
            this.weibull.setS(((Double) sSpinner.getValue()).doubleValue());
        }
}//GEN-LAST:event_sSpinnerStateChanged

    private void tSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tSpinnerStateChanged
        if (this.weibull != null) {
            this.weibull.setT(((Double) tSpinner.getValue()).doubleValue());
        }
}//GEN-LAST:event_tSpinnerStateChanged

private void sTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTypeComboBoxActionPerformed
    if(this.weibull != null) {
        this.weibull.setSTableEnabled(sTypeComboBox.getSelectedIndex() == 1);
        updateDisplay();
    }
}//GEN-LAST:event_sTypeComboBoxActionPerformed

private void tTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTypeComboBoxActionPerformed
    if(this.weibull != null) {
        this.weibull.setTTableEnabled(tTypeComboBox.getSelectedIndex() == 1);
        updateDisplay();
    }
}//GEN-LAST:event_tTypeComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aButtonGroup;
    private javax.swing.ButtonGroup bButtonGroup;
    private javax.swing.JSpinner sSpinner;
    private blue.soundObject.editor.jmask.TableEditor sTableEditor;
    private javax.swing.JComboBox sTypeComboBox;
    private javax.swing.JSpinner tSpinner;
    private blue.soundObject.editor.jmask.TableEditor tTableEditor;
    private javax.swing.JComboBox tTypeComboBox;
    // End of variables declaration//GEN-END:variables

    public void setDuration(double duration) {
        sTableEditor.setDuration(duration);
        tTableEditor.setDuration(duration);
    }
}
