/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blue.ui.core.globals;

import blue.GlobalOrcSco;
import blue.projects.BlueProject;
import blue.projects.BlueProjectManager;
import blue.ui.nbutilities.MimeTypeEditorComponent;
import blue.ui.utilities.SimpleDocumentListener;
import blue.undo.NoStyleChangeUndoManager;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.Serializable;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.undo.UndoManager;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class GlobalOrchestraTopComponent extends TopComponent {

    private static GlobalOrchestraTopComponent instance;

    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "GlobalOrchestraTopComponent";

    private GlobalOrcSco globalOrcSco = null;
    
    UndoManager undo = new NoStyleChangeUndoManager();

    MimeTypeEditorComponent editor;

    private GlobalOrchestraTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(GlobalOrchestraTopComponent.class, "CTL_GlobalOrchestraTopComponent"));
        setToolTipText(NbBundle.getMessage(GlobalOrchestraTopComponent.class, "HINT_GlobalOrchestraTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));

        editor = new MimeTypeEditorComponent("text/x-csound-orc");
        this.add(editor, BorderLayout.CENTER);
        
        BlueProjectManager.getInstance().addPropertyChangeListener(new PropertyChangeListener() {

            public void propertyChange(PropertyChangeEvent evt) {
                if (BlueProjectManager.CURRENT_PROJECT.equals(evt.
                        getPropertyName())) {
                    globalOrcSco = null;
                    reinitialize();
                }
            }
        });

        reinitialize();
        editor.setUndoManager(undo);

        editor.getDocument().addDocumentListener(new SimpleDocumentListener() {

            @Override
            public void documentChanged(DocumentEvent e) {
                if (globalOrcSco != null) {
                    globalOrcSco.setGlobalOrc(editor.getText());
                }
            }
        });
    }

    private void reinitialize() {
        BlueProject project = BlueProjectManager.getInstance().getCurrentProject();
        if (project == null) {
            editor.setText("");
            editor.getJEditorPane().setEditable(false);
        } else {
            GlobalOrcSco localGlobals = project.getData().getGlobalOrcSco();
            editor.setText(localGlobals.getGlobalOrc());
            editor.getJEditorPane().setEditable(true);
            globalOrcSco = localGlobals;
        }
        
        editor.getJEditorPane().setCaretPosition(0);
        editor.getDocument().addUndoableEditListener(undo);

        undo.discardAllEdits();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized GlobalOrchestraTopComponent getDefault() {
        if (instance == null) {
            instance = new GlobalOrchestraTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the GlobalOrchestraTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized GlobalOrchestraTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(GlobalOrchestraTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof GlobalOrchestraTopComponent) {
            return (GlobalOrchestraTopComponent) win;
        }
        Logger.getLogger(GlobalOrchestraTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return GlobalOrchestraTopComponent.getDefault();
        }
    }
}
