/*
 * blue - object composition environment for csound Copyright (c) 2000-2009
 * Steven Yi (stevenyi@gmail.com)
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License or (at your option) any
 * later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.LIB. If not, write to the Free
 * Software Foundation Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307
 * USA
 */
package blue.ui.core.score.layers.soundObject;

import blue.event.SelectionEvent;
import blue.plugin.BluePlugin;
import blue.soundObject.Instance;
import blue.soundObject.SoundObject;
import blue.soundObject.editor.ScoreObjectEditor;
import blue.ui.core.BluePluginManager;
import blue.ui.core.score.layers.SoundObjectProvider;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final public class ScoreObjectEditorTopComponent extends TopComponent
        implements LookupListener {

    private static ScoreObjectEditorTopComponent instance;
    /**
     * path to the icon used by the component and its open action
     */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "SoundObjectEditorTopComponent";

    JPanel editPanel = new JPanel();

    CardLayout cardLayout = new CardLayout();

    SoundObject currentSoundObject;

//    HashMap<Class, Class> sObjEditorMap = new HashMap<>();
//    HashMap<Class, ScoreObjectEditor> editors = new HashMap<>();
    List<ScoreObjectEditor> editors = new ArrayList<>();

    JPanel emptyPanel = new JPanel();

    Lookup.Result<SoundObject> result = null;

    private ScoreObjectEditorTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ScoreObjectEditorTopComponent.class,
                "CTL_ScoreObjectEditorTopComponent"));
        setToolTipText(NbBundle.getMessage(ScoreObjectEditorTopComponent.class,
                "HINT_ScoreObjectEditorTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
        emptyPanel.setMinimumSize(new Dimension(0, 0));
        this.setLayout(new BorderLayout());
        editPanel.setLayout(cardLayout);
        this.add(editPanel, BorderLayout.CENTER);
        editPanel.add(emptyPanel, "none");

        FileObject sObjEditorFiles[] = FileUtil.getConfigFile(
                "blue/score/objectEditors").getChildren();

        for (FileObject fObj : sObjEditorFiles) {
            ScoreObjectEditor sObjEditor = FileUtil.getConfigObject(
                    fObj.getPath(),
                    ScoreObjectEditor.class);
            editors.add(sObjEditor);
            editPanel.add(sObjEditor.getClass().getName(), sObjEditor);
        }

        setEditingLibraryObject(null);
        setActivatedNodes(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files
     * only, i.e. deserialization routines; otherwise you could get a
     * non-deserialized instance. To obtain the singleton instance, use
     * {@link #findInstance}.
     */
    public static synchronized ScoreObjectEditorTopComponent getDefault() {
        if (instance == null) {
            instance = new ScoreObjectEditorTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the ScoreObjectEditorTopComponent instance. Never call
     * {@link #getDefault} directly!
     */
    public static synchronized ScoreObjectEditorTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(
                PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(ScoreObjectEditorTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof ScoreObjectEditorTopComponent) {
            return (ScoreObjectEditorTopComponent) win;
        }
        Logger.getLogger(ScoreObjectEditorTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        result = Utilities.actionsGlobalContext().lookupResult(SoundObject.class);
        result.addLookupListener(this);
        resultChanged(null);
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
    }

    /**
     * replaces this in object stream
     */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return ScoreObjectEditorTopComponent.getDefault();
        }
    }

    @Override
    public void resultChanged(LookupEvent ev) {

        if (!(TopComponent.getRegistry().getActivated() instanceof SoundObjectProvider)) {
            return;
        }

        Collection<? extends SoundObject> soundObjects = result.allInstances();
        if (soundObjects.size() == 1) {
            editSoundObject(soundObjects.iterator().next());
            //FIXME - setEditingLibraryObject(...)
        } else {
            editSoundObject(null);
        }
    }

    public void setEditingLibraryObject(Object objectType) {
        String name = NbBundle.getMessage(ScoreObjectEditorTopComponent.class,
                "CTL_ScoreObjectEditorTopComponent");

        if (objectType == SelectionEvent.SELECTION_LIBRARY) {
            name += " - Library";
        } else if (objectType == SelectionEvent.SELECTION_BLUE_LIVE) {
            name += " - blue Live";
        }

        setName(name);
//        this.libraryEditLabel.setVisible(isLibaryObject);
    }

    public void editSoundObject(SoundObject sObj) {
        if (currentSoundObject == sObj) {
            return;
        }

        currentSoundObject = sObj;

        cardLayout.show(editPanel, "none");
        if (sObj == null) {
            // JOptionPane.showMessageDialog(null, "yo");
            return;
        }

        SoundObject sObjToEdit = sObj;

        if (sObj instanceof Instance) {
            sObjToEdit = ((Instance) sObj).getSoundObject();
            this.setEditingLibraryObject(SelectionEvent.SELECTION_LIBRARY);
        }

        boolean found = false;
        for (ScoreObjectEditor sObjEditor : editors) {
            if (sObjEditor.accepts(sObjToEdit)) {
                sObjEditor.editScoreObject(sObjToEdit);
                cardLayout.show(editPanel, sObjEditor.getClass().getName());
                found = true;
                break;
            }
        }

        if (!found) {
            DialogDisplayer.getDefault().notify(new NotifyDescriptor(
                    "Could not find editor for SoundObject of type: " + sObjToEdit.getClass().getCanonicalName(),
                    "Error",
                    NotifyDescriptor.DEFAULT_OPTION,
                    NotifyDescriptor.ERROR_MESSAGE, null, null));
            return;
        }

//        Logger.getLogger(ScoreObjectEditorTopComponent.class.getName()).fine("SoundObject Selected: " + className);;
    }
}
