package blue.ui.core.project;

import blue.BlueSystem;
import blue.ProjectProperties;
import blue.projects.BlueProjectManager;
import blue.ui.utilities.FileChooserManager;
import blue.ui.utilities.SimpleDocumentListener;
import java.io.IOException;
import javax.swing.event.DocumentEvent;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Exceptions;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author syyigmmbp
 */
public class MediaPanel extends javax.swing.JPanel {

    private ProjectProperties projectProperties;

    /**
     * Creates new form MediaPanel
     */
    public MediaPanel() {
        initComponents();

        mediaFolderTextField.getDocument().addDocumentListener(
                new SimpleDocumentListener() {

            @Override
            public void documentChanged(DocumentEvent e) {
                if (projectProperties != null) {
                    projectProperties.mediaFolder = mediaFolderTextField.getText();
                }
            }
        });
    }

    public void setProjectProperties(ProjectProperties projectProperties) {
        this.projectProperties = null;

        if (projectProperties != null) {
            mediaFolderTextField.setText(projectProperties.mediaFolder);
            this.projectProperties = projectProperties;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mediaFolderTextField = new javax.swing.JTextField();
        mediaFolderBrowseButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MediaPanel.class, "MediaPanel.jLabel1.text")); // NOI18N

        mediaFolderTextField.setText(org.openide.util.NbBundle.getMessage(MediaPanel.class, "MediaPanel.mediaFolderTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mediaFolderBrowseButton, org.openide.util.NbBundle.getMessage(MediaPanel.class, "MediaPanel.mediaFolderBrowseButton.text")); // NOI18N
        mediaFolderBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaFolderBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mediaFolderTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mediaFolderBrowseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediaFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediaFolderBrowseButton))
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mediaFolderBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaFolderBrowseButtonActionPerformed
        var fcm = FileChooserManager.getDefault();
        var currentProjectDir = BlueSystem.getCurrentProjectDirectory();

        if (currentProjectDir == null) {
            final var projectDir = BlueSystem.getCurrentProjectDirectory();
            
            if(projectDir == null || !projectDir.exists()) {
                var nd = new NotifyDescriptor("Please save this project before setting a media directory.", 
                        "Project not saved yet", NotifyDescriptor.DEFAULT_OPTION, 
                        NotifyDescriptor.ERROR_MESSAGE, 
                        null, null);
                DialogDisplayer.getDefault().notify(nd);
                return;
            }
        } else {
            fcm.setCurrentDirectory(this, currentProjectDir);
            fcm.setDirectoryChooser(this, true);
            var retVal = fcm.showOpenDialog(this, this);
            if (retVal != null && retVal.size() == 1) {
                try {
                    var f = retVal.get(0);
                    if(!f.isDirectory()) {
                        return;
                    }
                    var absFilePath = f.getCanonicalPath();
                    String relPath = BlueSystem.getRelativePath(absFilePath);
                    mediaFolderTextField.setText(relPath);
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }

            }
        }

    }//GEN-LAST:event_mediaFolderBrowseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mediaFolderBrowseButton;
    private javax.swing.JTextField mediaFolderTextField;
    // End of variables declaration//GEN-END:variables
}
